name: Fluisterbos - Vakantiewoning en Gelegenheidsadres in Oostende
markdown: redcarpet
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data"]
pygments: true
keywords:
  - Oostende
  - vakantiewoning
