name: Fluisterbos

markdown: redcarpet
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data"]
pygments: true

description: Vakantiewoning en Gelegenheidsadres in Oostende
url: http://www.fluisterbos.be
keywords:
  - Oostende
  - vakantiewoning
  - vakantiehuis
  - vakantieverblijf
  - vakantie
  - familie
  - arrangement
  - verblijf
  - erfgoed
  - fietsvriendelijk
  - luxe
  - grote groep
  - 14 personen
  - team building
  - mice
  - meeting
  - incentive
  - congres
  - event
  - cadeautip
  - zee
  - kust
  - strand
  - vakantie-aan-zee
  - Belgische kust
  - Vlaamse kust

