name: Fluisterbos

markdown: redcarpet
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data"]
pygments: true

description: Vakantiewoning en Gelegenheidsadres in Oostende
url: http://www.fluisterbos.be
keywords:
  - Oostende
  - vakantiewoning
  - vakantiehuis
  - vakantieverblijf
  - vakantie
  - familie
  - arrangement
  - verblijf
  - vakantie aan zee
  - Belgische kust
  - Vlaamse kust
